spring:
  h2:
    console:
      enabled: true

  session:
    store-type: jdbc  # 세션저장소로 DB를 사용하기 위함

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    oauth2:
      client:
        registration:
          client-id: test
            client-secret: test
            scope: profile, email
