spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/borabook;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true #system.out으로 출력함. 개발환경에서만 사용할 것.
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


logging:
  level:
    org.hibernate.SQL: debug #logger를 통해서 sql을 로깅함.
#    org.hibernate.type: trace