name: first-springboot2

on:
  push:
    branches:
      - master # (1) Github Action의 트리거 브랜치를 지정
  workflow_dispatch: # (2) 브랜치 push 이벤트외에, 수동으로 실행하는 것도 가능하게 만드는 옵션

jobs:
  build:
    runs-on: ubuntu-latest # (3) 해당 Github Action 스크립트가 작동될 OS 환경을 지정합니다.

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # (4) 프로젝트 코드를 checkout 합니다.

      - name: Set up JDK 11
        uses: actions/setup-java@v1 # (5) Github Action이 실행될 OS에 Java를 설치합니다.
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # (6) gradle wrapper를 실행할 수 있도록 실행 권한 (+x)을 줍니다.
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build # (7) gradle wrapper를 통해 해당 프로젝트를 build 합니다.
        shell: bash